name: Build image and publish it into the registry

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  unit_tests:
    name: Execute unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npm run test:ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: junit.xml             # Path to test results
          reporter: jest-junit        # Format of test results

